sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/exercism .
script:
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/exercism mix hex.outdated
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/exercism mix credo
  - docker run -it --rm --env MIX_ENV=dev jeremymiller/exercism mix dialyzer --no-compile --no-check --halt-exit-status
  - docker run -it --rm --env MIX_ENV=test jeremymiller/exercism mix test
after_script:
  - MIX_ENV=docs mix inch.report
